export enum NodeKind {
  // Root
  PROGRAM,

  // Statements
  VARIABLE_DECLARATION,
  WRITE_STATEMENT,
  IF_STATEMENT,
  LOOP_STATEMENT,
  BLOCK_STATEMENT,
  RETURN_STATEMENT,

  // Expressions
  IDENTIFIER,

  NUMBER_LITERAL,
  STRING_LITERAL,
  BOOLEAN_LITERAL,
  NULL_LITERAL,
  UNDEFINED_LITERAL,

  BINARY_EXPRESSION,
  UNARY_EXPRESSION,
}